version: "3.4"
services:
  foocommerce_web:
    build: .
    container_name: foocommerce
    ports:
      - "80:80"
    depends_on:
      - foocommerce_database

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  foocommerce_database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: foocommerce_mssql_server
    environment:
      SA_PASSWORD: "foocommerce_db_password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  foocommerce_data:
