version: '3.4'

services:
  web-client:
    image: "foocommerce/web-client"
    environment:
      ConnectionString: "sqlserver;Database=FooCommerce;User ID=sa;Password=%7BecNR%40xtY%7D0S;Persist Security Info=False;"
      DOTNET_RUNNING_IN_CONTAINER: "True"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: "Microsoft.AspNetCore.SpaProxy"
    ports:
      #- "5100:80" #{OutOfContainerPort:InContainerPort}
      - "44370:443" #{OutOfContainerPort:InContainerPort}
    build:
      context: .
      dockerfile: FooCommerce.Web/Dockerfile
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - sqlserver
      - rabbitmq
      - worker-notification
      - worker-membership

  worker-notification:
    image: "foocommerce/worker-notification"
    environment:
      ConnectionString: "sqlserver;Database=FooCommerce;User ID=sa;Password=%7BecNR%40xtY%7D0S;Persist Security Info=False;"
      DOTNET_RUNNING_IN_CONTAINER: "True"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5110:80" #{OutOfContainerPort:InContainerPort}
      - "5111:443" #{OutOfContainerPort:InContainerPort}
    build:
      context: .
      dockerfile: FooCommerce.NotificationAPI.Worker/Dockerfile
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - sqlserver
      - rabbitmq

  worker-membership:
    image: "foocommerce/worker-membership"
    environment:
      ConnectionString: "sqlserver;Database=FooCommerce;User ID=sa;Password=%7BecNR%40xtY%7D0S;Persist Security Info=False;"
      DOTNET_RUNNING_IN_CONTAINER: "True"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5120:80" #{OutOfContainerPort:InContainerPort}
      - "5121:443" #{OutOfContainerPort:InContainerPort}
    build:
      context: .
      dockerfile: FooCommerce.MembershipAPI.Worker/Dockerfile
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - sqlserver
      - rabbitmq

  sqlserver:
    image: "foocommerce/mssql-server:2019-latest"
    container_name: 'sqlserver'
    restart: on-failure
    ports:
      - 1433:1433
    #build:
    #  context: .
    #  dockerfile: FooCommerce.SQLScripts/Dockerfile # implements Full-Text Search to SQL Server 2019
    environment:
      MSSQL_AGENT_ENABLED: "True" # To enable Full-Text Search
      SA_PASSWORD: "{ecNR@xtY}0S" # Must be Super password
      ACCEPT_EULA: "Y"

  rabbitmq:
    image: "masstransit/rabbitmq:latest"
    container_name: rabbitmq
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672