version: "3.8"
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "client_db_password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  worker_notification:
    build:
      context: .
      dockerfile: ./FooCommerce.NotificationAPI/Dockerfile
    ports:
      - "81:81"
    depends_on:
      - sqlserver
      - rabbitmq
  client:
    build:
      context: .
      dockerfile: ./FooCommerce.Web/Dockerfile
    cpus: 1.5
    mem_limit: 2048m
    ports:
      - "80:80"
    depends_on:
      - sqlserver
      - rabbitmq
      - worker_notification

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  client_data:
