CREATE TABLE [dbo].[Settings]
(
	[Id] uniqueidentifier ROWGUIDCOL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    [Created] DATETIME2 DEFAULT GETUTCDATE() NOT NULL, 
    [RowVersion] ROWVERSION, 
	[Key] NVARCHAR(255) NOT NULL,
	[Value] NVARCHAR(255) NOT NULL,
)

GO

CREATE UNIQUE INDEX [IX_Settings_Id] ON [dbo].[Settings] ([Id])

GO

CREATE FULLTEXT INDEX ON [dbo].[Settings] ([Key]) KEY INDEX [IX_Settings_Id] ON [FullTextCatalog] WITH CHANGE_TRACKING AUTO
